version: "3"
services:
  app:
    image: "node:18-buster"
    container_name: "foodlink-api"
    networks:
      - nginx-network
    tty: true
    ports:
      - "31111:3000"
    volumes:
      - /home/foodlink-be:/home/foodlink-be

networks:
  nginx-network:
    external: true
