version: "3"
services:
  db:
    image: "node:18-alpine"
    container_name: "foodlink-api"
    networks:
      - nginx-network
    ports:
      - "31111:3000"
    restart: always
    volumes:
      - /home/foodlink-fe:/home/foodlink-fe
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"

networks:
  nginx-network:
    external: true
